workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "Spawn_Me.xcodeproj"
        XCODE_SCHEME: "Spawn_Me"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          # Install CocoaPods dependencies if needed
          # pod install
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - polsito@polsito.dev
